apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
  - ../../base

namePrefix: dev-

replicas:
  - name: saju-interpret
    count: 1

patches:
  - target:
      kind: Deployment
      name: saju-interpret
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "dev"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "512Mi"
